general {
    lock_cmd = caelestia shell lock lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300  # 5 mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600  # 10 mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1200  # 12 mins
    on-timeout = systemctl suspend-then-hibernate || loginctl suspend
}
